import * as fs from 'node:fs';
import * as path from 'node:path';
import { Command } from 'commander';
import {
    getXQoderPaths,
    logger,
} from '@xqoder/shared';

const SHARE_URL_PATTERN = /^https?:\/\//i;
import {
    SQLiteSessionStore,
    type AgentSessionStore,
    type PersistedSessionSummary,
} from '@xqoder/storage-sqlite';
import {
    createImportedSession,
    parseSessionExportDocument,
} from '../../features/sessions/assets.js';

interface ImportCommandDependencies {
    sessionStore?: Pick<AgentSessionStore, 'getSession' | 'saveSession'>;
}

interface ImportCommandOptions {
    dir?: string;
    cwd?: string;
    sessionId?: string;
    model?: string;
    title?: string;
}

export function createImportCommand(
    dependencies: ImportCommandDependencies = {},
): Command {
    return new Command('import')
        .description('Import a session JSON generated by xqoder export')
        .argument('<file>', 'Path to the import file')
        .option('-d, --dir <dir>', 'Target project root directory after import')
        .option('--cwd <cwd>', 'Target working directory after import')
        .option('-s, --session-id <id>', 'Override the session ID after import')
        .option('-m, --model <model>', 'Override the model after import')
        .option('--title <title>', 'Override the title after import')
        .action(async (file: string, options: ImportCommandOptions) => {
            try {
                await runImportCommand(file, options, dependencies);
            } catch (error) {
                logger.error(`Import failed: ${error instanceof Error ? error.message : String(error)}`);
                process.exit(1);
            }
        });
}

export async function runImportCommand(
    filePath: string,
    options: ImportCommandOptions,
    dependencies: ImportCommandDependencies = {},
): Promise<PersistedSessionSummary> {
    const sessionStore = dependencies.sessionStore ?? createDefaultSessionStore();
    const raw = await loadImportSource(filePath);
    const document = parseSessionExportDocument(raw);
    const resolvedProjectRoot = path.resolve(options.dir ?? document.summary.projectRoot);
    const resolvedCwd = path.resolve(options.cwd ?? options.dir ?? document.summary.cwd ?? resolvedProjectRoot);
    const targetSessionId = resolveImportedSessionId(
        sessionStore,
        document,
        options.sessionId,
    );
    const session = createImportedSession(document, targetSessionId);
    const summary = sessionStore.saveSession({
        session,
        projectRoot: resolvedProjectRoot,
        cwd: resolvedCwd,
        model: options.model?.trim() || document.summary.model,
        title: options.title?.trim() || document.summary.title,
    });

    logger.success(`Session imported: ${summary.id}`);
    return summary;
}

export const importCommand = createImportCommand();

function createDefaultSessionStore(): AgentSessionStore {
    return new SQLiteSessionStore(getXQoderPaths().sessionDbFile);
}

async function loadImportSource(source: string): Promise<unknown> {
    if (SHARE_URL_PATTERN.test(source.trim())) {
        const res = await fetch(source.trim(), {
            headers: { Accept: 'application/json' },
        });
        if (!res.ok) {
            throw new Error(`Failed to import from URL: ${res.status} ${res.statusText}`);
        }
        return res.json() as Promise<unknown>;
    }
    return JSON.parse(fs.readFileSync(path.resolve(source), 'utf-8')) as unknown;
}

function resolveImportedSessionId(
    sessionStore: Pick<AgentSessionStore, 'getSession'>,
    document: ReturnType<typeof parseSessionExportDocument>,
    preferredId?: string,
): string {
    const normalizedPreferredId = preferredId?.trim();
    if (normalizedPreferredId) {
        return normalizedPreferredId;
    }

    const existing = sessionStore.getSession(document.snapshot.id);
    if (!existing) {
        return document.snapshot.id;
    }

    return `session_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}
