import * as fs from 'node:fs';
import * as path from 'node:path';
import { Command } from 'commander';
import {
    getXQoderPaths,
    logger,
} from '@xqoder/shared';

const MAX_IMPORT_SIZE_BYTES = 5 * 1024 * 1024;
import {
    SQLiteSessionStore,
    type AgentSessionStore,
    type PersistedSessionSummary,
} from '@xqoder/storage-sqlite';
import {
    createImportedSession,
    parseSessionExportDocument,
} from '../../features/sessions/assets.js';
import { checkUrlSafety } from '../../core/agent/tools/url-safety.js';

interface ImportCommandDependencies {
    sessionStore?: Pick<AgentSessionStore, 'getSession' | 'saveSession'>;
}

interface ImportCommandOptions {
    dir?: string;
    cwd?: string;
    sessionId?: string;
    model?: string;
    title?: string;
}

export function createImportCommand(
    dependencies: ImportCommandDependencies = {},
): Command {
    return new Command('import')
        .description('Import a session JSON generated by xqoder export')
        .argument('<file>', 'Path to the import file')
        .option('-d, --dir <dir>', 'Target project root directory after import')
        .option('--cwd <cwd>', 'Target working directory after import')
        .option('-s, --session-id <id>', 'Override the session ID after import')
        .option('-m, --model <model>', 'Override the model after import')
        .option('--title <title>', 'Override the title after import')
        .action(async (file: string, options: ImportCommandOptions) => {
            try {
                await runImportCommand(file, options, dependencies);
            } catch (error) {
                logger.error(`Import failed: ${error instanceof Error ? error.message : String(error)}`);
                process.exit(1);
            }
        });
}

export async function runImportCommand(
    filePath: string,
    options: ImportCommandOptions,
    dependencies: ImportCommandDependencies = {},
): Promise<PersistedSessionSummary> {
    const sessionStore = dependencies.sessionStore ?? createDefaultSessionStore();
    const raw = await loadImportSource(filePath);
    const document = parseSessionExportDocument(raw);
    const resolvedProjectRoot = path.resolve(options.dir ?? document.summary.projectRoot);
    const resolvedCwd = path.resolve(options.cwd ?? options.dir ?? document.summary.cwd ?? resolvedProjectRoot);
    const targetSessionId = resolveImportedSessionId(
        sessionStore,
        document,
        options.sessionId,
    );
    const session = createImportedSession(document, targetSessionId);
    const summary = sessionStore.saveSession({
        session,
        projectRoot: resolvedProjectRoot,
        cwd: resolvedCwd,
        model: options.model?.trim() || document.summary.model,
        title: options.title?.trim() || document.summary.title,
    });

    logger.success(`Session imported: ${summary.id}`);
    return summary;
}

export const importCommand = createImportCommand();

function createDefaultSessionStore(): AgentSessionStore {
    return new SQLiteSessionStore(getXQoderPaths().sessionDbFile);
}

export interface LoadImportSourceOptions {
    fetchImpl?: typeof fetch;
    resolveIps?: (hostname: string) => Promise<string[]>;
}

export async function loadImportSource(
    source: string,
    options: LoadImportSourceOptions = {},
): Promise<unknown> {
    const trimmed = source.trim();
    if (/^[a-zA-Z][a-zA-Z0-9+.-]*:\/\//.test(trimmed)) {
        return loadImportSourceFromUrl(trimmed, options);
    }
    return JSON.parse(fs.readFileSync(path.resolve(source), 'utf-8')) as unknown;
}

async function loadImportSourceFromUrl(
    url: string,
    options: LoadImportSourceOptions,
): Promise<unknown> {
    const safetyOpts: { allowHttp: false } & Pick<LoadImportSourceOptions, 'resolveIps'> = {
        allowHttp: false,
        ...(options.resolveIps ? { resolveIps: options.resolveIps } : {}),
    };
    const safety = await checkUrlSafety(url, safetyOpts);
    if (safety.allowed === false) {
        throw new Error(`Refusing to import from URL: ${safety.reason}`);
    }

    const fetchImpl = options.fetchImpl ?? fetch;
    const res = await fetchImpl(url, {
        headers: { Accept: 'application/json' },
    });
    if (!res.ok) {
        throw new Error(`Failed to import from URL: ${res.status} ${res.statusText}`);
    }

    const contentType = res.headers.get('content-type') ?? '';
    if (!/^application\/json\b/i.test(contentType)) {
        throw new Error(`Refusing import: expected application/json content-type, got "${contentType || '<none>'}"`);
    }

    const contentLengthRaw = res.headers.get('content-length');
    if (contentLengthRaw !== null) {
        const contentLength = Number(contentLengthRaw);
        if (Number.isFinite(contentLength) && contentLength > MAX_IMPORT_SIZE_BYTES) {
            throw new Error(
                `Refusing import: response size ${contentLength} bytes exceeds cap ${MAX_IMPORT_SIZE_BYTES} bytes`,
            );
        }
    }

    const body = await res.text();
    if (body.length > MAX_IMPORT_SIZE_BYTES) {
        throw new Error(
            `Refusing import: response body ${body.length} bytes exceeds cap ${MAX_IMPORT_SIZE_BYTES} bytes`,
        );
    }
    return JSON.parse(body) as unknown;
}

function resolveImportedSessionId(
    sessionStore: Pick<AgentSessionStore, 'getSession'>,
    document: ReturnType<typeof parseSessionExportDocument>,
    preferredId?: string,
): string {
    const normalizedPreferredId = preferredId?.trim();
    if (normalizedPreferredId) {
        return normalizedPreferredId;
    }

    const existing = sessionStore.getSession(document.snapshot.id);
    if (!existing) {
        return document.snapshot.id;
    }

    return `session_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}
