/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CellStyle {
  fg?: string
  bg?: string
  bold?: boolean
  dim?: boolean
  italic?: boolean
  underline?: boolean
  strikethrough?: boolean
}
export interface MouseEvent {
  kind: string
  button: string
  col: number
  row: number
  shift: boolean
  alt: boolean
  ctrl: boolean
  velocity: number
}
export interface LayoutRect {
  x: number
  y: number
  width: number
  height: number
}
export interface TuiLayout {
  header: LayoutRect
  messages: LayoutRect
  messagesScrollbar?: LayoutRect
  input: LayoutRect
  footer: LayoutRect
  sidebar: LayoutRect
  hasSidebar: boolean
  overlay?: LayoutRect
}
export interface ViewportRange {
  startLine: number
  endLine: number
}
export interface ScrollbarThumb {
  visible: boolean
  thumbTop: number
  thumbHeight: number
  trackHeight: number
}
export interface EntryHeightCache {
  heights: Array<number>
  cumHeights: Array<number>
  totalLines: number
}
export interface HitTargetResult {
  kind: string
  lineOffset?: number
  row?: number
  ratio?: number
  index?: number
  id?: string
}
export interface MessageHeightsResult {
  heights: Array<number>
  cumHeights: Array<number>
  totalLines: number
}
export interface VisibleMessageRangeResult {
  startIndex: number
  startLineOffset: number
  endIndex: number
}
export interface InputPartSpec {
  kind: string
  content?: string
  display?: string
  agentId?: string
  wordCount?: number
  index?: number
}
export interface InputLayoutResult {
  lines: Array<string>
  styledLines: Array<InputStyledLine>
  cursorLine: number
  cursorCol: number
  borderTone: string
  borderGlyph: string
  modeChipText: string
  modeChipTone: string
  promptFirst: string
  promptContinuation: string
  contentOffsetFirst: number
  contentOffsetContinuation: number
  cornerTl: string
  cornerTr: string
  cornerBl: string
  cornerBr: string
  sideGlyph: string
  isPlaceholder: boolean
}
export interface InputStyledSegment {
  text: string
  tone: string
}
export interface InputStyledLine {
  segments: Array<InputStyledSegment>
}
export interface MessagePart {
  kind: string
  content?: string
  toolName?: string
  status?: string
  summary?: string
  collapsed?: boolean
  items?: Array<string>
  actionId?: string
  stepIndex?: number
  stepTotal?: number
  label?: string
}
export interface Message {
  id: string
  role: string
  parts: Array<MessagePart>
  timestamp: number
}
export interface TuiState {
  page: string
  logLines: Array<string>
  messages?: Array<Message>
  input: TuiInputState
  sidebar: TuiSidebarState
  status: TuiStatusState
  scroll: TuiScrollState
  layout: TuiLayout
  overlay?: TuiOverlayState
  tick: number
  blink: boolean
}
export interface TuiOverlayState {
  kind: string
  items: Array<string>
  selectedIndex: number
  scrollOffset: number
  maxWidth?: number
}
export interface TuiInputState {
  parts: Array<InputPartSpec>
  cursorGrapheme: number
  mode: string
}
export interface TuiSidebarState {
  sessionId: string
  cwd: string
  model: string
  agent: string
  mode: string
  contextUsed: number
  contextMax: number
  costUsdThis: number
  costUsdToday: number
  todayMessages: number
  lspLines: Array<string>
  dockerLines: Array<string>
  dockerUrl: string
}
export interface TuiStatusState {
  thinking: boolean
  text: string
}
export interface TuiScrollState {
  offsetLines: number
  maxScrollY: number
  contentLines: number
  stickyBottom: boolean
  draggingScrollbar: boolean
}
export declare function ping(): string
export declare function computeTuiLayout(cols: number, rows: number, inputLines: number, overlayItemCount?: number | undefined | null, overlayMaxWidth?: number | undefined | null): TuiLayout
export declare function wrapTextToWidth(text: string, maxWidth: number): Array<string>
export declare function computeViewportVisibleRange(lineCount: number, topLine: number, height: number): ViewportRange
export declare function computeScrollbarThumb(contentHeight: number, viewportHeight: number, scrollTop: number, trackHeight: number): ScrollbarThumb
export declare function resolveViewportTopLineFromScrollbar(lineCount: number, height: number, pointerRow: number, dragOffset: number): number
export declare function resolveViewportTopLineForJump(lineCount: number, height: number, targetLine: number, anchorNumerator: number, anchorDenominator: number): number
export declare function buildEntryHeightCache(starts: Array<number>, ends: Array<number>): EntryHeightCache
export declare function findEntryRangeIndex(starts: Array<number>, ends: Array<number>, line: number): number
export declare function hitTest(cols: number, rows: number, inputLines: number, overlayItemCount: number | undefined | null, overlayMaxWidth: number | undefined | null, col: number, row: number): HitTargetResult
export declare function computeMessageHeights(messages: Array<string>, contentWidth: number): MessageHeightsResult
export declare function findVisibleMessageRange(cumHeights: Array<number>, heights: Array<number>, scrollOffset: number, viewportHeight: number): VisibleMessageRangeResult
export declare function renderInputParts(parts: Array<InputPartSpec>, cursorGrapheme: number, maxWidth: number, mode: string, placeholder: string): InputLayoutResult
export declare function isFoldedDiffMarker(line: string): boolean
export declare function foldedMarkerHiddenCount(line: string): number
export declare function isContextReadTool(toolName: string): boolean
export declare function contextGroupLabel(reads: number): string
export declare function inertialScrollDeltas(delta: number, steps: number): Array<number>
export declare class XqRenderer {
  constructor(cols: number, rows: number)
  writeText(col: number, row: number, text: string, style: CellStyle): void
  clearLine(row: number): void
  clear(): void
  invalidate(): void
  resize(cols: number, rows: number): void
  stringWidth(text: string): number
  truncateToWidth(text: string, maxWidth: number): string
  parseMouse(seq: string): MouseEvent | null
  mouseEnableAnsi(): string
  mouseDisableAnsi(): string
  decayScroll(): number
  resetScroll(): void
  scrollVelocity(): number
  commitState(state: TuiState): void
  snapshotFrameLines(): Array<string>
  snapshotFrameStyledLines(): Array<string>
  handleMouse(seq: string, inputLines: number): boolean
  handleMouseEvent(event: MouseEvent, inputLines: number): boolean
  messageScrollBy(delta: number): void
  messageScrollPageUp(pageSize: number): void
  messageScrollPageDown(pageSize: number): void
  messageScrollHome(): void
  messageScrollToBottom(): void
  messageScrollOffsetLines(): number
  messageScrollStickyBottom(): boolean
  messageScrollSetTopLine(topLine: number): void
  messageScrollSetFromScrollbar(lineCount: number, height: number, pointerRow: number, dragOffset: number): void
  messageScrollJumpTo(lineCount: number, height: number, targetLine: number, anchorNumerator: number, anchorDenominator: number): void
  logScrollRefresh(logLines: Array<string>, contentWidth: number, viewportHeight: number): void
  logScrollBy(delta: number): void
  logScrollPageUp(pageSize: number): void
  logScrollPageDown(pageSize: number): void
  logScrollHome(): void
  logScrollToBottom(): void
  logScrollOffsetLines(): number
  logScrollStickyBottom(): boolean
  logScrollSetTopLine(topLine: number): void
  logScrollSetFromScrollbar(lineCount: number, height: number, pointerRow: number, dragOffset: number): void
}
